[package]
name = "yesterday"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"

[dependencies.hooky]
path = "../.."
features = ["use_parking_lot"]
